import numpy as np
print('**************** Ejercicios Python ***************')

print('ejercicio 2')
print('Version ' + np.__version__)
#np.show_config()
print('ejercicio 3')
Z = np.zeros(10)
print(Z)
print('ejercicio 5')
Z = np.zeros(10)
Z[4] = 1
print(Z)
print('ejercicio 6')
Z = np.arange(10,50)
print(Z)
print('ejercicio 7')
N = np.arange(50)
print('Original')
print(N)
print('Reverse')
N= N[::-1] #para generar reversa
print(N)
print('ejercicio 8')
W= np.arange(9).reshape(3,3)
print(W)
print('ejercicio 9')
nz = np.nonzero([1,2,0,0,4,0])
print(nz)
print('ejercicio 10')
Z = np.eye(3)
print(Z)
print('ejercicio 11 crear con valores aleatorios')
Z = np.random.random((3,3,3))*10
print(Z)
print('ejercicio 12 imprimir minimo y maximo')
Z = np.random.random((10,10))
Zmin, Zmax = Z.min(), Z.max()
print(Zmin, Zmax)
print('ejercicio 13 vector aleatorio, tamaño 30')
Z = np.random.random(30)
m = Z.mean()
print(m)
print('ejercicio 14 1 en el borde, 0 en el interior')
Z = np.ones((10,10))
Z[1:-1,1:-1] = 0
print(Z)
print('ejercicio 15 1 en el borde, 0 en el interior')
print(np.nan)
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3 * 0.1)
print(np.inf)
